prometheus:
  prometheusSpec:
    additionalAlertManagerConfigs:
      - static_configs:
          - targets: [
            "alertmanager.monitoring.svc.cluster.local:9093"
          ]
        scheme: http