prometheus:
  prometheusSpec:
    additionalAlertManagerConfigs:
      - static_configs:
          - targets: [
            "alertmanager-0-access.alertmanager.svc.cluster.local:9093",
            "alertmanager-1-access.alertmanager.svc.cluster.local:9093"
          ]
        scheme: http
