apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lab-prometheus-crds
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=default"]
  generators:
    - list:
        elements:
        - name: in-cluster
          server: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.name}}-prometheus-crds'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/prometheus-operator/prometheus-operator.git'
        targetRevision: v0.70.0
        path: example/prometheus-operator-crd
      destination:
        server: '{{.server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true