apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertmanager
  namespace: alertmanager
  labels:
    app: alertmanager
spec:
  serviceName: "alertmanager-headless"
  replicas: 2
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      containers:
      # 1. Container Principal do Alertmanager
      - name: alertmanager
        image: quay.io/prometheus/alertmanager:v0.27.0 # Use a tag de vers√£o mais recente/desejada
        args:
        - --config.file=/etc/alertmanager/config.yaml
        - --log.level=debug
        - --storage.path=/alertmanager
        - --cluster.listen-address=0.0.0.0:6783
        - --web.listen-address=0.0.0.0:9093
        ports:
        - containerPort: 9093
          name: http-web
          protocol: TCP
        - containerPort: 9094
          name: meh-tcp
          protocol: TCP
        - containerPort: 9094
          name: meh-udp
          protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: storage
          mountPath: /alertmanager
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

      - name: config-reloader
        image: quay.io/prometheus-operator/prometheus-config-reloader:v0.87.0
        args:
          - --watch-interval=30s
          - --config-file=/etc/alertmanager/config.yaml
          - --reload-url=http://127.0.0.1:9093/-/reload
        volumeMounts:
          - name: config-volume
            mountPath: /etc/alertmanager
        resources:
          limits:
            cpu: 100m
            memory: 128Mi

      volumes:
      - name: config-volume
        secret:
            secretName: alertmanager-config-secret
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
